version: "3.7"
services:
  grpc-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: grpc-server
    environment:
      - "GRPC_PORT=6666"
      - "MY_POD_IP=0.0.0.0"
    ports:
      - "6666:6666"
  grpc-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: grpc-client
    environment:
      - "HTTP_PORT=8888"
      - "GRPC_HOST_ADDR=34.84.8.190:50051"
    ports:
      - "8888:8888"
    depends_on:
      - grpc-server